/*
SANITY CMS PAUSED

Projects now use local MDX plus src/data/projects.ts metadata. Keep this schema
as the reconnect map for the old localized Sanity document structure.

import { defineType, defineField } from 'sanity'

export const project = defineType({
  name: 'project',
  title: 'Project',
  type: 'document',
  fields: [
    defineField({
      name: 'slugEn',
      title: 'Slug (English)',
      type: 'slug',
      options: { source: 'titleEn', maxLength: 96 },
      group: 'en',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'slugEs',
      title: 'Slug (Spanish)',
      type: 'slug',
      options: { source: 'titleEs', maxLength: 96 },
      group: 'es',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'slugDe',
      title: 'Slug (German)',
      type: 'slug',
      options: { source: 'titleDe', maxLength: 96 },
      group: 'de',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'slugUr',
      title: 'Slug (Urdu)',
      type: 'slug',
      options: { source: 'titleUr', maxLength: 96 },
      group: 'ur',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'titleEn',
      title: 'Title (English)',
      type: 'string',
      group: 'en',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'titleEs',
      title: 'Title (Spanish)',
      type: 'string',
      group: 'es',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'titleDe',
      title: 'Title (German)',
      type: 'string',
      group: 'de',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'titleUr',
      title: 'Title (Urdu)',
      type: 'string',
      group: 'ur',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'descriptionEn',
      title: 'Description (English)',
      type: 'text',
      rows: 3,
      group: 'en',
    }),
    defineField({
      name: 'descriptionEs',
      title: 'Description (Spanish)',
      type: 'text',
      rows: 3,
      group: 'es',
    }),
    defineField({
      name: 'descriptionDe',
      title: 'Description (German)',
      type: 'text',
      rows: 3,
      group: 'de',
    }),
    defineField({
      name: 'descriptionUr',
      title: 'Description (Urdu)',
      type: 'text',
      rows: 3,
      group: 'ur',
    }),
    defineField({
      name: 'contentEn',
      title: 'Content (English)',
      type: 'array',
      of: [{ type: 'block' }],
      group: 'en',
    }),
    defineField({
      name: 'contentEs',
      title: 'Content (Spanish)',
      type: 'array',
      of: [{ type: 'block' }],
      group: 'es',
    }),
    defineField({
      name: 'contentDe',
      title: 'Content (German)',
      type: 'array',
      of: [{ type: 'block' }],
      group: 'de',
    }),
    defineField({
      name: 'contentUr',
      title: 'Content (Urdu)',
      type: 'array',
      of: [{ type: 'block' }],
      group: 'ur',
    }),
    defineField({
      name: 'projectUrl',
      title: 'Project URL',
      type: 'url',
    }),
    defineField({
      name: 'githubUrl',
      title: 'GitHub URL',
      type: 'url',
    }),
    defineField({
      name: 'technologies',
      title: 'Technologies',
      type: 'array',
      of: [{ type: 'string' }],
    }),
    defineField({
      name: 'imageUrl',
      title: 'Image URL',
      type: 'url',
    }),
    defineField({
      name: 'featuresEn',
      title: 'Features (English)',
      type: 'array',
      of: [{ type: 'string' }],
      group: 'en',
    }),
    defineField({
      name: 'featuresEs',
      title: 'Features (Spanish)',
      type: 'array',
      of: [{ type: 'string' }],
      group: 'es',
    }),
    defineField({
      name: 'featuresDe',
      title: 'Features (German)',
      type: 'array',
      of: [{ type: 'string' }],
      group: 'de',
    }),
    defineField({
      name: 'featuresUr',
      title: 'Features (Urdu)',
      type: 'array',
      of: [{ type: 'string' }],
      group: 'ur',
    }),
    defineField({
      name: 'challengesEn',
      title: 'Challenges (English)',
      type: 'array',
      of: [{ type: 'string' }],
      group: 'en',
    }),
    defineField({
      name: 'challengesEs',
      title: 'Challenges (Spanish)',
      type: 'array',
      of: [{ type: 'string' }],
      group: 'es',
    }),
    defineField({
      name: 'challengesDe',
      title: 'Challenges (German)',
      type: 'array',
      of: [{ type: 'string' }],
      group: 'de',
    }),
    defineField({
      name: 'challengesUr',
      title: 'Challenges (Urdu)',
      type: 'array',
      of: [{ type: 'string' }],
      group: 'ur',
    }),
    defineField({
      name: 'lessonsEn',
      title: 'Lessons Learned (English)',
      type: 'array',
      of: [{ type: 'string' }],
      group: 'en',
    }),
    defineField({
      name: 'lessonsEs',
      title: 'Lessons Learned (Spanish)',
      type: 'array',
      of: [{ type: 'string' }],
      group: 'es',
    }),
    defineField({
      name: 'lessonsDe',
      title: 'Lessons Learned (German)',
      type: 'array',
      of: [{ type: 'string' }],
      group: 'de',
    }),
    defineField({
      name: 'lessonsUr',
      title: 'Lessons Learned (Urdu)',
      type: 'array',
      of: [{ type: 'string' }],
      group: 'ur',
    }),
  ],
  groups: [
    { name: 'en', title: 'English', default: true },
    { name: 'es', title: 'Spanish' },
    { name: 'de', title: 'German' },
    { name: 'ur', title: 'Urdu' },
  ],
})
*/

export {}
